[package]
name = "salsa"
version = "0.0.1"
authors = [ "DrDelphi" ]
edition = "2021"
publish = false

[lib]
path = "src/salsa.rs"

[dev-dependencies]
num-bigint = "0.4.3"

[dependencies.multiversx-sc]
version = "0.41.1"

[dependencies.multiversx-sc-modules]
version = "0.41.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.41.1"

[dependencies]
hex-literal = "0.3.1"
