[package]
name = "salsa"
version = "0.0.3"
authors = [ "DrDelphi" ]
edition = "2021"
publish = false

[lib]
path = "src/salsa.rs"

[dev-dependencies]
num-bigint = "0.4.3"

[dependencies.multiversx-sc]
version = "0.45.2"

[dependencies.multiversx-sc-modules]
version = "0.45.2"

[dev-dependencies.multiversx-sc-scenario]
version = "0.45.2"

[dependencies]
hex-literal = "0.3.1"

[dependencies.delegation-mock]
path = "./delegation-mock"

[workspace]
members = [
    ".",
    "./meta",
    "delegation-mock",
    "delegation-mock/meta"
]
