// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           43
// Async Callback:                       1
// Total number of exported functions:  45

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    salsa
    (
        delegate
        unDelegate
        withdraw
        addReserve
        removeReserve
        unDelegateNow
        distributeProfit
        setArbitrageActive
        registerLiquidToken
        getLiquidTokenId
        getLiquidTokenSupply
        setStateActive
        setStateInactive
        getState
        setProviderAddress
        getProviderAddress
        getUnbondPeriod
        setUnbondPeriod
        getUserUndelegations
        getTotalEgldStaked
        getUserWithdrawnEgld
        getTotalWithdrawnEgld
        getTotalUserUndelegations
        getEgldReserve
        getReservePoints
        getAvailableEgldReserve
        getReserveUndelegations
        getUsersReservePoints
        setUndelegateNowFee
        getUndelegateNowFee
        getReservePointsAmount
        getReserveEgldAmount
        getUserReserve
        setArbitrageInactive
        getArbitrageState
        getLiquidProfit
        getEgldProfit
        getTokenPrice
        unDelegateAll
        compound
        withdrawAll
        computeWithdrawn
        setOnedexPairId
        callBack
    )
}
