// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xstake_mock
    (
        init => init
        upgrade => upgrade
        createStake => create_stake
        setStakeState => set_stake_state
        addStakeRewards => add_stake_rewards
        withdrawStakeRewards => withdraw_stake_rewards
        changeStakeEnd => change_stake_end
        setState => set_state
        getState => state
        getStakeState => get_stake_state
        getLastStakeID => last_stake_id
        getStakes => get_stakes
        getStake => get_stake
        getStakers => stakers
        getUserStake => get_user_stake
        getAllUserStakes => all_user_stakes
        userStake => user_stake
        userUnstake => user_unstake
        claimRewards => claim_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
