// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           53
// Async Callback:                       1
// Total number of exported functions:  55

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    onedex_mock
    (
        init => init
        upgrade => upgrade
        setConfig => set_config
        setTotalFeePercent => set_total_fee_percent
        setSpecialFeePercent => set_special_fee_percent
        setStakingRewardFeePercent => set_staking_reward_fee_percent
        setStakingRewardAddress => set_staking_reward_address
        setTreasuryAddress => set_treasury_address
        setBurnerAddress => set_burner_address
        setUnwrapAddress => set_unwrap_address
        setRegisteringCost => set_registering_cost
        addMainPair => add_main_pair
        removeMainPair => remove_main_pair
        getMainPairTokens => main_pair_tokens
        getTotalFeePercent => total_fee_percent
        getSpecialFeePercent => special_fee_percent
        getStakingRewardFeePercent => staking_reward_fee_percent
        getTreasuryAddreess => treasury_address
        getStakingRewardAddress => staking_reward_address
        getBurnerAddreess => burner_address
        getUnwrapAddreess => unwrap_address
        getRegisteringCost => registering_cost
        getPaused => paused
        getPairIds => pair_ids
        getLastPairId => last_pair_id
        getLpTokenPairIdMap => lp_token_pair_id_map
        getPairOwner => pair_owner
        getPairState => pair_state
        getPairEnabled => pair_enabled
        getPairFirstTokenId => pair_first_token_id
        getPairSecondTokenId => pair_second_token_id
        getPairFirstTokenReserve => pair_first_token_reserve
        getPairSecondTokenReserve => pair_second_token_reserve
        getPairLpTokenId => pair_lp_token_id
        getPairLpTokenTotalSupply => pair_lp_token_supply
        enableSwap => enable_swap
        createPair => create_pair
        issueLpToken => issue_lp_token
        setLpTokenLocalRoles => set_lp_token_local_roles
        setPairActive => set_pair_active
        setPairActiveButNoSwap => set_pair_no_swaps
        setPairInactive => set_pair_inactive
        addInitialLiquidity => add_initial_liquidity
        addLiquidity => add_liquidity
        removeLiquidity => remove_liquidity
        swapMultiTokensFixedInput => swap_multi_tokens_fixed_input
        swapMultiTokensFixedOutput => swap_multi_tokens_fixed_output
        getEquivalent => get_equivalent
        getMultiPathAmountOut => get_multi_path_amount_out
        getAmountOut => get_amount_out_view
        getMultiPathAmountIn => get_multi_path_amount_in
        getAmountIn => get_amount_in_view
        viewPairs => view_pairs
        viewPair => view_pair
    )
}

multiversx_sc_wasm_adapter::async_callback! { onedex_mock }
