// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    delegation_mock
    (
        init => init
        delegate => delegate
        unDelegate => undelegate
        withdraw => withdraw
        reDelegateRewards => redelegate_rewards
        claimRewards => claim_rewards
        getClaimableRewards => get_claimable_rewards
        getUserActiveStake => get_user_active_stake
        getDelegatorFundsData => get_delegator_funds_data
        getContractConfig => get_contract_config
        getAllNodeStates => get_all_nodes_states
        getTotalActiveStake => get_total_active_stake
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
